name: my_dbt_project
version: 1.0.0
config-version: 2

# DBT profile to use
profile: my_dbt_project

# Paths
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

# --------------------------------------------------
# Model configuration
# --------------------------------------------------
models:
  my_dbt_project:
    +enabled: true
    +materialized: table  

    # Silver models folder
    silver:
      +enabled: true
      +materialized: table

    # Gold models folder
    gold:
      +enabled: true
      +materialized: table
